### ISSUE TITLE
401 on SkypeImageMsg.fileContent

### ISSUE THREAD

**Issue by dstelzer** [OllieTerrance/SkPy#46]
When I try to get the fileContent of a SkypeImageMsg or SkypeFileMsg, I get this response

     [traceback details in my own app]
     File "/usr/local/lib/python3.5/dist-packages/skpy/msg.py", line 498, in fileContent
        auth=SkypeConnection.Auth.Authorize).content
      File "/usr/local/lib/python3.5/dist-packages/skpy/conn.py", line 215, in __call__
        raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
     skpy.core.SkypeApiException: ('401 response from GET https://api.asm.skype.com/v1/objects/0-eus-d2-9fc51dfcc7c37f83eac51aa51031ceb3/views/imgpsh_fullsize', <Response [401]>)

I'm not sure what to do about this. Is it the wrong authentication method?

**Comment by OllieTerrance** [comment]
Can't seem to reproduce here.  Please set `SKPY_DEBUG_HTTP=1` in your environment, try retrieving the file again, and include the response from Skype below.

```shell
$ cat a.txt
A
```

```python
>>> m
SkypeFileMsg(...)
>>> m.file
File(name='a.txt', size='2', ...)
>>> m.fileContent
<= [28/02 10:29:24] GET https://api.asm.skype.com/v1/objects/0-weu-d2-.../views/original
{}
=> [28/02 10:29:25] 200
A
b'A\n'
```

**Comment by OllieTerrance** [comment]
@dstelzer: Any updates here?

**Comment by OllieTerrance** [comment]
Tried it again but can't see any way to reproduce this...  😞

**Comment by dstelzer** [comment]
Here's what I saw with HTTP debugging.

`[snip]
{'clientmessageid': '8611425457298071227',
               'composetime': '2017-03-30T22:21:53.953Z',
               'content': '<URIObject type="Picture.1" '
                          'uri="https://api.asm.skype.com/v1/objects/0-cus-d4-f4633e3c29a1bbd194f4a3a46d800dd4" '
                          'url_thumbnail="https://api.asm.skype.com/v1/objects/0-cus-d4-f4633e3c29a1bbd194f4a3a46d800dd4/views/imgt1" '
                          'ams_id="0-cus-d4-f4633e3c29a1bbd194f4a3a46d800dd4">You\'ve '
                          'received a new picture. View it at: <a '
                          'href="https://login.skype.com/login/sso?go=xmmfallback?pic=0-cus-d4-f4633e3c29a1bbd194f4a3a46d800dd4">https://login.skype.com/login/sso?go=xmmfallback?pic=0-cus-d4-f4633e3c29a1bbd194f4a3a46d800dd4</a><FileSize '
                          'v="146231" /><OriginalName v="" /><meta '
                          'type="photo" originalName="" /></URIObject>',
               'conversationLink': 'https://bn2-client-s.gateway.messenger.live.com/v1/users/ME/conversations/19:7ee9adcf32bb4e54af644413d4b08b80@thread.skype',
               'from': 'https://bn2-client-s.gateway.messenger.live.com/v1/users/ME/contacts/8:live:[username_redacted]',
               'id': '1490912513963',
               'messagetype': 'RichText/UriObject',
               'originalarrivaltime': '2017-03-30T22:21:53.953Z',
               'type': 'Message',
               'version': '1490912513963'}]}

<= [06/04 20:39:00] GET https://api.asm.skype.com/v1/objects/0-cus-d4-f4633e3c29a1bbd194f4a3a46d800dd4/views/imgpsh_fullsize
{}
=> [06/04 20:39:01] 401`

Strangely enough, waiting a couple minutes and trying again can sometimes avoid this problem.

(Also, successfully downloading an image with HTTP debugging on often does strange things to my terminal. But I don't know if there's a way to avoid that.)

**Comment by OllieTerrance** [comment]
Presumably the [fallback link](https://login.skype.com/login/sso?go=xmmfallback?pic=0-cus-d4-f4633e3c29a1bbd194f4a3a46d800dd4) in there works for you?  (I get an expired error but that's probably just masking the account mismatch -- if you get one now, try a fresh file upload first and test the corresponding link.)  If that fails too, it's probably Skype serving you a dud file for some reason.

If you're signed in to [Skype for Web](https://web.skype.com), the [direct file link](https://api.asm.skype.com/v1/objects/0-cus-d4-f4633e3c29a1bbd194f4a3a46d800dd4/views/imgpsh_fullsize) should also just work in your browser (it only appears to require cookies for auth).

```
<= [06/04 20:39:00] GET https://api.asm.skype.com/v1/objects/0-cus-d4-f4633e3c29a1bbd194f4a3a46d800dd4/views/imgpsh_fullsize
{}
=> [06/04 20:39:01] 401
```

Have you missed a line under that?  Presumably you didn't get the file, but did you get any form of response?  Usually Skype APIs give a JSON error response...

Curiously, following your link, I get redirected to `nus1-api.asm.skype.com` and the same path, and then get a 403, as opposed to a file of mine that has no such redirect.

> (Also, successfully downloading an image with HTTP debugging on often does strange things to my terminal. But I don't know if there's a way to avoid that.)

Indeed, that would be it trying to print binary files to your terminal.  If you just send text files around whilst testing, you should be ok.

**Comment by wilder11** [comment]
hi, I have also same problem.
however this happens on Centos 7 Ubuntu seems to work ok.
============================================
Traceback (most recent call last):
  File "./andy.py", line 36, in <module>
    sk.loop()
  File "/usr/lib64/python2.7/site-packages/skpy/main.py", line 218, in loop
    self.cycle()
  File "/usr/lib64/python2.7/site-packages/skpy/main.py", line 207, in cycle
    self.onEvent(event)
  File "./andy.py", line 21, in onEvent
    print event.msg.fileContent
  File "/usr/lib64/python2.7/site-packages/skpy/util.py", line 227, in wrapper
    cache[key] = fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/skpy/msg.py", line 593, in fileContent
    auth=SkypeConnection.Auth.Authorize).content
  File "/usr/lib64/python2.7/site-packages/skpy/conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('401 response from GET https://api.asm.skype.com/v1/objects/0-cus-d2-1f8840328850101b4d1631f4552d5653/views/imgpsh_fullsize', <Response [401]>)
======================================================

**Comment by OllieTerrance** [comment]
There's no differences with SkPy between the two OSes, nor should Skype be able to detect any due to the consistent user agent.  Please follow the previous requests to reproduce the issue with debugging, and to confirm if the fallback link still works.

**Comment by Ashymad** [comment]
I'm having the exact same problem. 
With SKPY_DEBUG_HTTP set to 1:
1. Getting the message (its a text file with "test" inside):
```
>>> m = sk.chats['8:username'].getMsgs()
<= [15/10 21:29:59] GET https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:username/messages?syncState=250c000000383a732e6d696b756c69637a01831072875e010000a43ef1215f01000000&startTime=0&view=msnp24Equivalent
{'params': {}}
=> [15/10 21:29:59] 200
{'Cache-Control': 'no-store, must-revalidate, no-cache',
 'Content-Encoding': 'gzip',
 'Content-Length': '634',
 'Content-Type': 'application/json; charset=utf-8',
 'ContextId': 'tcid=8250543446289258611,server=DB5SCH101101028',
 'Date': 'Sun, 15 Oct 2017 21:29:58 GMT',
 'Pragma': 'no-cache',
 'X-Content-Type-Options': 'nosniff'}
{'_metadata': {'lastCompleteSegmentEndTime': 1508102999127,
               'lastCompleteSegmentStartTime': 1505510953091,
               'syncState': 'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:username/messages?syncState=250c000000383a732e6d696b756c69637a01831072875e010000578cf1215f01000000&startTime=0&view=msnp24Equivalent'},
 'messages': [{'clientmessageid': '1508102989845',
               'composetime': '2017-10-15T21:29:52.373Z',
               'content': '<URIObject type="File.1" '
                          'uri="https://api.asm.skype.com/v1/objects/0-weu-d3-4bd84805043a69cec674293762cced9d" '
                          'url_thumbnail="https://api.asm.skype.com/v1/objects/0-weu-d3-4bd84805043a69cec674293762cced9d/views/thumbnail"><Title>Title: '
                          'test.txt</Title><Description> Description: '
                          'test.txt</Description><a '
                          'href="https://login.skype.com/login/sso?go=webclient.xmm&amp;docid=0-weu-d3-4bd84805043a69cec674293762cced9d"> '
                          'https://login.skype.com/login/sso?go=webclient.xmm&amp;docid=0-weu-d3-4bd84805043a69cec674293762cced9d</a><OriginalName '
                          'v="test.txt"/><FileSize v="5"/></URIObject>',
               'conversationLink': 'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:username',
               'conversationid': '8:username',
               'from': 'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/contacts/8:username',
               'id': '1508102992377',
               'messagetype': 'RichText/Media_GenericFile',
               'originalarrivaltime': '2017-10-15T21:29:52.373Z',
               'type': 'Message',
               'version': '1508102992377'}]}

```
2.  Downloading the file:
```
>>> m[0].fileContent
<= [15/10 21:42:01] GET https://api.asm.skype.com/v1/objects/0-weu-d3-4bd84805043a69cec674293762cced9d/views/original
{}
=> [15/10 21:42:02] 401
{'Content-Length': '0',
 'Date': 'Sun, 15 Oct 2017 21:42:01 GMT',
 'Server': 'Microsoft-IIS/8.5',
 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
 'X-Content-Type-Options': 'nosniff',
 'X-Powered-By': 'ARR/2.5, ASP.NET'}

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shyman/.pyenv/versions/skycord/lib/python3.6/site-packages/skpy/util.py", line 227, in wrapper
    cache[key] = fn(*args, **kwargs)
  File "/home/shyman/.pyenv/versions/skycord/lib/python3.6/site-packages/skpy/msg.py", line 568, in fileContent
    auth=SkypeConnection.Auth.Authorize).content
  File "/home/shyman/.pyenv/versions/skycord/lib/python3.6/site-packages/skpy/conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('401 response from GET https://api.asm.skype.com/v1/objects/0-weu-d3-4bd84805043a69cec674293762cced9d/views/original', <Response [401]>)
```
If I open the api.asm.skype.com link in a browser I can download the file no problem. Opening the fallback link in browser shows me "This is your message" and a play button, pressing it does nothing.

**Comment by OllieTerrance** [comment]
Let's reopen this as it's clearly affecting multiple users, despite not being reproducible over here.  🙁

**Comment by OllieTerrance** [comment]
> Opening the fallback link in browser shows me "This is your message" and a play button

Assuming that's still test.txt, I have no idea why a play button appears...

@Ashymad, @wilder11: Can you try sending a file through Skype for Web, and then capturing and downloading it from SkPy?  You can run a `SkypeEventLoop` and react to a `SkypeNewMessageEvent` where the event's `msg` property is a `SkypeFileMsg`, then try retrieving the content like before.

**Comment by Ashymad** [comment]
Here is the code I used:
```python
from skpy import *

class MySkype(SkypeEventLoop):
    def onEvent(self, event):
        if event.type == "NewMessage":
            if event.msg.type == "RichText/Media_GenericFile":
                file = event.msg.fileContent


username = "BotAccount"
password = ""

Skype(username,password,".tokens-test")

MySkypeLoop = MySkype(tokenFile=".tokens-test", autoAck=True)
MySkypeLoop.loop()
```
Then:
```bash
export SKPY_DEBUG_HTTP=1
python ./test.py > test.log 2>&1
```
Then I've sent a text file from my account (through Skype for Web) to the bot.
Here is [test.log](https://gist.github.com/Ashymad/eab12e4000ccb4b86cc123ebdd4b5158)
Maybe the problem is that I am running the script on a remote server?

**Comment by OllieTerrance** [comment]
Ok, so it looks like it's at least parsing the message correctly, but we're sending the wrong kind of credentials.  It's possible something has changed within Skype for Web, in which case it may be using different authentication now.

If you've still got that message hanging around, can you try using https://web.skype.com to fetch the attachment?  Open developer tools, try to download the file, find the request in the Network tab (on Chrome at least), and get a copy of the request headers and body.

**Comment by Ashymad** [comment]
Request headers:
```
GET /v1/objects/0-weu-d3-50424a9ccc973ea131da4209652afa83/views/original HTTP/1.1
Host: api.asm.skype.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://web.skype.com/en/
Cookie: SC=CC=:CCY=:LC=en:LIM=:RS=d:TM=1508355247:TS=1506340084:TZ=:VAT=:VER=; SWADCC=TS=1506340091:TM=1506340091; SWACC=TS=1506626683:TM=1506626683; SSP=linux; MSFPC=ID=63ce316bcc101742b49adbda8785d49d&CS=1&LV=201709&V=1; skype-cookie-policy=1; MSCC=1506756172; s_pers=%20s_fid%3D5A081F7341145EFA-11333A4437F17D54%7C1570361758933%3B%20gpv_p23%3Dno%2520value%7C1507291558935%3B%20s_nr%3D1507289758936-Repeat%7C1570361758936%3B; skypetoken_asm=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEzIn0.eyJpYXQiOjE1MDgzNTUyNDUsImV4cCI6MTUwODQ0MTY0Mywic2t5cGVpZCI6ImxpdmU6bjk5ODUxMCIsInNjcCI6OTU4LCJjc2kiOiIxIiwiY2lkIjoiZTNhZDQ0OWExMzhiODViMyIsImFhdCI6MTUwODM1NTA5NX0.cuTcXXQkY2eNi-_SUOynXZGoTD5Rx0Gm_GXGYwpecx4uf5iUJPeLEdKJWMu5ae8wQZz8jVP2b7EZWEcoIhwYigrL54t27RBe6KA6HMyzvpxSKRqDl8aDcZGhhM2kp5mqR61xVf0xXJgqG5fLmsWUu-dN_39QBhG45Vkv1OxhRc_NEOedroMoHZvEsKUZ0aedVFFiWnYR0ITjFgqm; platformid_asm=908; skplet=1508441645
Connection: keep-alive
Upgrade-Insecure-Requests: 1
DNT: 1
```
Response headers:
```
HTTP/1.1 200 OK
Cache-Control: no-cache, max-age=0, s-maxage=0, private
Content-Range: bytes 0-4/5
Server: Microsoft-IIS/8.5
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Content-Disposition: attachment; filename=test.txt
X-Powered-By: ARR/2.5, ASP.NET
Date: Wed, 18 Oct 2017 19:34:24 GMT
Content-Length: 5
```
Response:
```
test
```
I've also tried
```
curl 'https://api.asm.skype.com/v1/objects/0-weu-d3-50424a9ccc973ea131da4209652afa83/views/original' -H 'Host: api.asm.skype.com' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://web.skype.com/en/' -H 'Cookie: SC=CC=:CCY=:LC=en:LIM=:RS=d:TM=1508355247:TS=1506340084:TZ=:VAT=:VER=; SWADCC=TS=1506340091:TM=1506340091; SWACC=TS=1506626683:TM=1506626683; SSP=linux; MSFPC=ID=63ce316bcc101742b49adbda8785d49d&CS=1&LV=201709&V=1; skype-cookie-policy=1; MSCC=1506756172; s_pers=%20s_fid%3D5A081F7341145EFA-11333A4437F17D54%7C1570361758933%3B%20gpv_p23%3Dno%2520value%7C1507291558935%3B%20s_nr%3D1507289758936-Repeat%7C1570361758936%3B; skypetoken_asm=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEzIn0.eyJpYXQiOjE1MDgzNTUyNDUsImV4cCI6MTUwODQ0MTY0Mywic2t5cGVpZCI6ImxpdmU6bjk5ODUxMCIsInNjcCI6OTU4LCJjc2kiOiIxIiwiY2lkIjoiZTNhZDQ0OWExMzhiODViMyIsImFhdCI6MTUwODM1NTA5NX0.cuTcXXQkY2eNi-_SUOynXZGoTD5Rx0Gm_GXGYwpecx4uf5iUJPeLEdKJWMu5ae8wQZz8jVP2b7EZWEcoIhwYigrL54t27RBe6KA6HMyzvpxSKRqDl8aDcZGhhM2kp5mqR61xVf0xXJgqG5fLmsWUu-dN_39QBhG45Vkv1OxhRc_NEOedroMoHZvEsKUZ0aedVFFiWnYR0ITjFgqm; platformid_asm=908; skplet=1508441645' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'DNT: 1'
```
with mixed success. At first I didn't get anything then an unknown SSL protocol error, finally it started working.
After I did that, SkPy suddenly was able to download files and images as well...

**Comment by OllieTerrance** [comment]
Ugh.  I wonder if there's another API call that needs to be made first, before the link in the message becomes valid (after which both Skype for Web and SkPy can use it because the account / session is "authorised").

**Comment by Ashymad** [comment]
Today SkPy is able to download again. For no reason at all.I was not at home even, but my bot on the server suddenly became able to download them.

**Comment by dforsell** [comment]
I ran into the same problem. I have done a little troubleshooting and it appears there is a similar issue as with login.skype.com failing to redirect to api.asm.skype.com; in this case api.asm.skype.com fails to redirect to the proper "cloud server" resulting in the file not being found and returning a 401.

I did a silly little mod to get around this problem by first trying urlFull as returned from the API, and if that doesn't work I step through a ladder of exceptions for each API-server that I have identified so far, until I find the correct one for my file. If all fail I just leave it. Ugly I know, but it works for now. ;)

From what I have seen so far these are the servers api.asm.skype.com redirects to:
nus1-api.asm.skype.com
weu1-api.asm.skype.com
neu1-api.asm.skype.com
as-api.asm.skype.com
sa1-api.asm.skype.com
eus1-api.asm.skype.com
ea1-api.asm.skype.com

**Comment by OllieTerrance** [comment]
> there is a similar issue as with login.skype.com failing to redirect to api.asm.skype.com; in this case api.asm.skype.com

Is that from opening the fallback link in the message in a browser, or from opening a file directly from Skype for Web, or both?

> I step through a ladder of exceptions for each API-server that I have identified so far

There's bound to be another way to figure out where a file is.  Not sure how they're allocated -- if you send multiple files, are they consistently on the same file server?  IIRC I've personally only ever seen weu1 and neu1 from my testing.

**Comment by SergeiMinaev** [comment]
I'm having same issue. It happens sometimes and I absolutely have no idea why. It doesn't happen in web skype.

**Comment by SergeiMinaev** [comment]
Some strange logs:
```
>>> sk.conn
SkypeConnection(userId='live:blablabla', tokenFile='token', connected=True, guest=False)
>>> url = "https://weu1-api.asm.skype.com/v1/objects/bla/views/original"
>>> sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
  File "/media/work/envs/mtbz/lib/python3.5/site-packages/skpy/conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('400 response from GET https://weu1-api.asm.skype.com/v1/objects/bla/
views/original', <Response [400]>)
>>> 
>>> url = "https://weu1-api.asm.skype.com/v1/objects/bla/views/imgpsh_fullsize"
>>> sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
<Response [200]>
>>> sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
<Response [200]>
>>>
>>> url = "https://weu1-api.asm.skype.com/v1/objects/bla/views/original"
>>> sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
  File "/media/work/envs/mtbz/lib/python3.5/site-packages/skpy/conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('400 response from GET https://weu1-api.asm.skype.com/v1/objects/bla/
views/original', <Response [400]>)
>>> 
```

Looks like we should use /views/imgpsh_fullsize instead of /views/original! But...

```
>>> url
'https://api.asm.skype.com/v1/objects/bla/views/imgpsh_fullsize'
>>> sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
  File "/media/work/envs/mtbz/lib/python3.5/site-packages/skpy/conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('401 response from GET https://api.asm.skype.com/v1/objects/bla/views
/imgpsh_fullsize', <Response [401]>)
>>>
>>> url = "https://api.asm.skype.com/v1/objects/bla/views/original"
>>> sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
  File "/media/work/envs/mtbz/lib/python3.5/site-packages/skpy/conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('401 response from GET https://api.asm.skype.com/v1/objects/0-weu-d10-f82deea033cef2fc326c77e42300cc92/views
/original', <Response [401]>)
```

**Comment by SergeiMinaev** [comment]
I've noticed that problematic urls contains name of server. Like this:
urlFull: https://api.asm.skype.com/v1/objects/0-weu-d3-759ce324c4d88734b603e03cbde1333d
urlView: https://login.skype.com/login/sso?go=webclient.xmm&pic=0-weu-d3-759ce324c4d88734b603e03cbde1333d

It contains "**-weu**-".  I open first one in browser it returns 401 error. When I open second one it returns 200 and redirects to **weu**1-api.asm.skype.com.
So if I replace api.asm.skype.com with weu1-api.asm.skype.com it loads fine.

Same in python shell:

```
>>> url = "https://{0}api.asm.skype.com/v1/objects/{1}/views/imgpsh_fullsize".format('', '0-weu-d3-759ce324c4d88734b603e03cbde1333d')
>>> sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
  File "/media/work/envs/mtbz/lib/python3.5/site-packages/skpy/conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('401 response from GET https://api.asm.skype.com/v1/objects/0-weu-d3-759ce324c4d88734b603e03cbde1333d/views/imgpsh_fullsiz
e', <Response [401]>)
>>> 
>>> 
>>> url = "https://{0}api.asm.skype.com/v1/objects/{1}/views/imgpsh_fullsize".format('weu1-', '0-weu-d3-759ce324c4d88734b603e03cbde1333d')
>>> sk.conn("GET", url, auth=sk.conn.Auth.Authorize)
<Response [200]>
>>> 
```
According to @dforsell there is a lot of servers. Also seems like all image urls contains /0-something-d. We can do some dirty trick like this:

```
>>> import re
>>> url = 'https://api.asm.skype.com/v1/objects/0-weu-d3-759ce324c4d88734b603e03cbde1333d'
>>> img_id = re.search('v1/objects/(.+)', url).group(1)
>>> name = re.search('0-([A-Za-z0-9]+)-d', img_id).group(1)
>>> new_url = 'https://'+name+'1-api.asm.skype.com/v1/objects/'+img_id
>>> sk.conn("GET", new_url, auth=sk.conn.Auth.Authorize)
<Response [200]>
>>>
``` 
I know it looks ugly but seems like it works :) Need more testing ofc.

**Comment by Ashymad** [comment]
I'm testing your hack, @SergeiMinaev , and it seems to work.

**Comment by OllieTerrance** [comment]
Interesting, I wonder which clients are generating the dud links then.  I suppose Skype for Web rewrites them somewhere, similar to the workaround above.

I'm going to be off the grid for the rest of this week, but I'll take a proper look after that.  Hopefully, if it proves successful, I'll get such a workaround in place.  🙂

**Comment by OllieTerrance** [comment]
Based on @SergeiMinaev's sample above, I've pushed a potential fix to the [`file-url-fix` branch](https://github.com/OllieTerrance/SkPy/tree/file-url-fix).

For those who have seen issues reading file content from messages, please try this branch and report back on whether it works for you or not.

I'm not particularly happy on using `{server-id}1-asm.skype.com` as the hostname (with `server-id` extracted from the object URL) as this feels rather brittle, so I'm keen to hear if there are any server names that don't satisfy this pattern (@dforsell mentioned `as-api.asm.skype.com` so I'm unsure if/when that will come up).  So far I've only come across weu1 and neu1 during my testing.

**Comment by Ashymad** [comment]
I've been testing the fix for the last week or so and everything is working quite nicely.

**Comment by OllieTerrance** [comment]
I've merged it as-is for lack of a better solution.  Hopefully this puts us in a better position than without.

**Comment by goaucomp** [comment]
I still see this error in 0.10.6

An error occurred: 401 Client Error: Unauthorized for url: https://api.asm.skype.com/v1/objects/0-sa-d1-86d6de52532838282bd170491a147ffc/views/original

**Comment by goaucomp** [comment]
Can you please help if there is a workaround to get rid of this error 401 ?

**Comment by Terrance** [comment]
If you try to download the same file in Skype for Web, what does the URL look like?

**Comment by goaucomp** [comment]
This is as seen from the browser 

Request URL:
https://gateway.bingviz.microsoftapp.net/receive?app=skype
Request Method:
POST
Status Code:
200 OK

**Comment by goaucomp** [comment]
Prior to the above request there was a 

Request URL:
https://gateway.bingviz.microsoftapp.net/receive?app=skype
Request Method:
OPTIONS
Status Code:
204 No Content

**Comment by Terrance** [comment]
`gateway.bingviz.microsoftapp.net` appears to be client analytics/tracking and is unrelated to downloading images.  I'd expect the request you're looking for to look like the one SkPy is trying to make but on a different domain.

**Comment by goaucomp** [comment]
I tried another instance of download from the code and the browser(skype web). The URL that is being used seems to be the same in both the case.

code:

An error occurred: 401 Client Error: Unauthorized for url: https://api.asm.skype.com/v1/objects/0-sa-d6-d1754454c51db5164aa91d2078ae8983/views/original

skype web:

Refer attachment.

Pasted below 'Copy -> Copy all as cURL (cmd)'  of the highlighted network packet in the attachment:

curl "https://azwcus1-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/^%^7B054b6547-1b60-4b9f-a21f-bdcd061aec24^%^7D/active" ^
  -H "Accept: application/json" ^
  -H "Accept-Language: en-US,en;q=0.9" ^
  -H "Authentication: skypetoken=eyJhbGciOiJSUzI1NiIsImtpZCI6IjVFODQ4MjE0Qzc3MDczQUU1QzJCREU1Q0NENTQ0ODlEREYyQzRDODQiLCJ4NXQiOiJYb1NDRk1kd2M2NWNLOTVjelZSSW5kOHNUSVEiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2OTY1NjYxMTUsImV4cCI6MTY5NjY1MjUxMywic2t5cGVpZCI6ImxpdmU6LmNpZC43ZWY2NDNlZjczNzNlOWUzIiwic2NwIjo5NTgsImNzaSI6IjE2OTY1NjYxMTMiLCJjaWQiOiI3ZWY2NDNlZjczNzNlOWUzIiwiYWF0IjoxNjk2MjM4NjcwfQ.cHYiY5m941BZAtkRviFbsbgGPKy5UVAWlpqgtk6g7tqLMHLz2VzkEZXVseIW-24czOTPNuJu9s-vXM1hHX9fxVQRSu-FQDN78GMjdj_tuht0gGL73OJrQWRDtwdfIVJUp5HksmqYyUTfpqUgpeRmYH-V7M1Aj1YgXzXhzGP41YIgKcmTcGMDq7RsJPICnVCgLxHnFGWCOp00GnoA_m22yXZjX2roesPpDm2UcqrwhGtjMndcp7kY5tUUywyqvIbtwU4cTsyHqmpROJw_Vnzcb2I6AwC3DQl3SgzXyQ9UhukmwUMuzKwF4sDpddXUulTh-F-ZN_JFHO_YdHSoN0ou_A" ^
  -H "BehaviorOverride: redirectAs404" ^
  -H "ClientInfo: os=Windows; osVer=10; proc=x86; lcid=en-US; deviceType=1; country=IN; clientName=skype4life; clientVer=1418/8.105.0.208//skype4life; timezone=Asia/Calcutta" ^
  -H "Connection: keep-alive" ^
  -H "Content-Type: application/json" ^
  -H "EndpointId: ^{054b6547-1b60-4b9f-a21f-bdcd061aec24^}" ^
  -H "Origin: https://web.skype.com" ^
  -H "Referer: https://web.skype.com/" ^
  -H "RegistrationToken: registrationToken=U2lnbmF0dXJlOjI6Mjg6QVFRQUFBRDRqbFo5c3ZWYTF3aXBCQ25HTi9rSztWZXJzaW9uOjY6MToxO0lzc3VlVGltZTo0OjE5OjUyNTAwMDc2NDc2MzA3NTIwNjk7RXAuSWRUeXBlOjc6MTo4O0VwLklkOjI6MjY6bGl2ZTouY2lkLjdlZjY0M2VmNzM3M2U5ZTM7RXAuRXBpZDo1OjM2OjA1NGI2NTQ3LTFiNjAtNGI5Zi1hMjFmLWJkY2QwNjFhZWMyNDtFcC5Mb2dpblRpbWU6NzoxOjA7RXAuQXV0aFRpbWU6NDoxOTo1MjUwMDA3NjQ3NjMwNzUyMDY5O0VwLkF1dGhUeXBlOjc6MjoxNTtFcC5FeHBUaW1lOjQ6MTk6NTI1MDAwODUxMTU1NzM4NzkwNDtFcC5Ta3lwZVRva2VuOjI6Njg4OmV5SmhiR2NpT2lKU1V6STFOaUlzSW10cFpDSTZJalZGT0RRNE1qRTBRemMzTURjelFVVTFRekpDUkVVMVEwTkVOVFEwT0RsRVJFWXlRelJET0RRaUxDSjROWFFpT2lKWWIxTkRSazFrZDJNMk5XTkxPVFZqZWxaU1NXNWtPSE5VU1ZFaUxDSjBlWEFpT2lKS1YxUWlmUS5leUpwWVhRaU9qRTJPVFkxTmpZeE1UVXNJbVY0Y0NJNk1UWTVOalkxTWpVeE15d2ljMnQ1Y0dWcFpDSTZJbXhwZG1VNkxtTnBaQzQzWldZMk5ETmxaamN6TnpObE9XVXpJaXdpYzJOd0lqbzVOVGdzSW1OemFTSTZJakUyT1RZMU5qWXhNVE1pTENKamFXUWlPaUkzWldZMk5ETmxaamN6TnpObE9XVXpJaXdpWVdGMElqb3hOamsyTWpNNE5qY3dmUS5jSFlpWTVtOTQxQlpBdGtSdmlGYnNiZ0dQS3k1VVZBV2xwcWd0azZnN3RxTE1ITHoyVnprRVpYVnNlSVctMjRjek9UUE51SnU5cy12WE0xaEhYOWZ4VlFSU3UtRlFETjc4R01qZGpfdHVodDBnR0w3M09KclFXUkR0d2RmSVZKVXA1SGtzbXFZeVVUZnBxVWdwZVJtWUgtVjdNMUFqMVlnWHpYaHpHUDQxWUlnS2NtVGNHTURxN1JzSlBJQ25WQ2dMeEhuRkdXQ09wMDBHbm9BX20yMnlYWmpYMnJvZXNQcERtMlVjcXJ3aEd0ak1uZGNwN2tZNXRVVXl3eXF2SWJ0d1U0Y1RzeUhxbXBST0p3X1ZuemNiMkk2QXdDM0RRbDNTZ3pYeVE5VWh1a213VU11ekt3RjRzRHBkZFhVdWxUaC1GLVpOX0pGSE9fWWRIU29OMG91X0E7VXNyLk5ldE1hc2s6MTE6MToyO1Vzci5YZnJDbnQ6NjoxOjA7VXNyLlJkcmN0RmxnOjI6MDo7VXNyLkV4cElkOjk6MTowO1Vzci5FeHBJZExhc3RMb2c6NDoxOjA7VXNlci5BdGhDdHh0OjI6NDQ4OkNsTnJlWEJsVkc5clpXNGFiR2wyWlRvdVkybGtMamRsWmpZME0yVm1Oek0zTTJVNVpUTUJBMVZwWXhReEx6RXZNREF3TVNBeE1qb3dNRG93TUNCQlRReE9iM1JUY0dWamFXWnBaV1RqNlhOejcwUDJmZ0FBQUFBQUFFQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQWFiR2wyWlRvdVkybGtMamRsWmpZME0yVm1Oek0zTTJVNVpUTUFBQUFBQUFBQUFBQUhUbTlUWTI5eVpRQUFBQUFFQUFBQUFBQUFBQUFBQUFEajZYTno3MFAyZmdBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQVJwc2FYWmxPaTVqYVdRdU4yVm1OalF6WldZM016Y3paVGxsTXdBQUFBQUFZWXNmWlFnQUFBQURWV2xqQ0Vsa1pXNTBhWFI1RGtsa1pXNTBhWFI1VlhCa1lYUmxDRU52Ym5SaFkzUnpEa052Ym5SaFkzUnpWWEJrWVhSbENFTnZiVzFsY21ObERVTnZiVzExYm1sallYUnBiMjRWUTI5dGJYVnVhV05oZEdsdmJsSmxZV1JQYm14NUFBQT07; expires=1696652513; endpointId=^{054b6547-1b60-4b9f-a21f-bdcd061aec24^}" ^
  -H "Sec-Fetch-Dest: empty" ^
  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Site: cross-site" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" ^
  -H "X-ECS-Etag: ^\^"ZJLCvwIoVVVrLRRR/TDjZd2NJChqUI1ksJdavyLuOyg=^\^"" ^
  -H "sec-ch-ua: ^\^"Google Chrome^\^";v=^\^"117^\^", ^\^"Not;A=Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"117^\^"" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
  --data-raw "^{^\^"timeout^\^":120^}" ^
  --compressed &
curl "https://api.asm.skype.com/v1/objects/0-sa-d6-d1754454c51db5164aa91d2078ae8983/views/original/status" ^
  -X "OPTIONS" ^
  -H "authority: api.asm.skype.com" ^
  -H "accept: */*" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "access-control-request-headers: authorization,correlationid,requestid,x-client-version" ^
  -H "access-control-request-method: GET" ^
  -H "origin: https://web.skype.com" ^
  -H "referer: https://web.skype.com/" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: same-site" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" ^
  --compressed &
curl "https://api.asm.skype.com/v1/objects/0-sa-d6-d1754454c51db5164aa91d2078ae8983/views/original/status" ^
  -H "authority: api.asm.skype.com" ^
  -H "accept: application/json" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "authorization: skype_token eyJhbGciOiJSUzI1NiIsImtpZCI6IjVFODQ4MjE0Qzc3MDczQUU1QzJCREU1Q0NENTQ0ODlEREYyQzRDODQiLCJ4NXQiOiJYb1NDRk1kd2M2NWNLOTVjelZSSW5kOHNUSVEiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2OTY1NjYxMTUsImV4cCI6MTY5NjY1MjUxMywic2t5cGVpZCI6ImxpdmU6LmNpZC43ZWY2NDNlZjczNzNlOWUzIiwic2NwIjo5NTgsImNzaSI6IjE2OTY1NjYxMTMiLCJjaWQiOiI3ZWY2NDNlZjczNzNlOWUzIiwiYWF0IjoxNjk2MjM4NjcwfQ.cHYiY5m941BZAtkRviFbsbgGPKy5UVAWlpqgtk6g7tqLMHLz2VzkEZXVseIW-24czOTPNuJu9s-vXM1hHX9fxVQRSu-FQDN78GMjdj_tuht0gGL73OJrQWRDtwdfIVJUp5HksmqYyUTfpqUgpeRmYH-V7M1Aj1YgXzXhzGP41YIgKcmTcGMDq7RsJPICnVCgLxHnFGWCOp00GnoA_m22yXZjX2roesPpDm2UcqrwhGtjMndcp7kY5tUUywyqvIbtwU4cTsyHqmpROJw_Vnzcb2I6AwC3DQl3SgzXyQ9UhukmwUMuzKwF4sDpddXUulTh-F-ZN_JFHO_YdHSoN0ou_A" ^
  -H "correlationid: bfff1247-7a04-4718-9b17-237d9a5db9e0" ^
  -H "origin: https://web.skype.com" ^
  -H "referer: https://web.skype.com/" ^
  -H "requestid: c16af9c4-54ca-46b3-bd42-19435fd672e0" ^
  -H "sec-ch-ua: ^\^"Google Chrome^\^";v=^\^"117^\^", ^\^"Not;A=Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"117^\^"" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: same-site" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" ^
  -H "x-client-version: 1418/8.105.0.208//" ^
  --compressed &
curl "https://gateway.bingviz.microsoftapp.net/receive?app=skype" ^
  -X "OPTIONS" ^
  -H "authority: gateway.bingviz.microsoftapp.net" ^
  -H "accept: */*" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "access-control-request-headers: content-type" ^
  -H "access-control-request-method: POST" ^
  -H "origin: https://web.skype.com" ^
  -H "referer: https://web.skype.com/" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: cross-site" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" ^
  --compressed &
curl "https://gateway.bingviz.microsoftapp.net/receive?app=skype" ^
  -H "authority: gateway.bingviz.microsoftapp.net" ^
  -H "accept: */*" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "content-type: application/json" ^
  -H "origin: https://web.skype.com" ^
  -H "referer: https://web.skype.com/" ^
  -H "sec-ch-ua: ^\^"Google Chrome^\^";v=^\^"117^\^", ^\^"Not;A=Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"117^\^"" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: cross-site" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" ^
  --data-raw "^{^\^"dvid^\^":^\^"732b6fd7-ef81-49f0-9c10-b1e80a30033c^\^",^\^"meta^\^":^{^\^"advertisingId^\^":^\^"^\^",^\^"applicationId^\^":^\^"32EE78B3360B43588BFCD9818E60BBED^\^",^\^"build^\^":^\^"1418/8.105.0.208^\^",^\^"clientVersion^\^":^\^"8.105.0.208^\^",^\^"deviceModel^\^":^\^"Chrome^\^",^\^"deviceType^\^":^\^"117.0.0.0^\^",^\^"installId^\^":^\^"abc92135-33b0-4bfb-ad42-5a3a9f315381^\^",^\^"market^\^":^\^"en-US^\^",^\^"os^\^":^\^"Windows^\^",^\^"osVersion^\^":^\^"10^\^",^\^"timezone^\^":^\^"Asia/Calcutta^\^",^\^"extSchema^\^":^{^\^"user^\^":^{^\^"userSignedIn^\^":true,^\^"signinAccount^\^":^\^"S4LLive^\^",^\^"skypeId^\^":^\^"7EF643EF7373E9E3^\^"^}^},^\^"configuration^\^":^\^"1418^\^",^\^"flights^\^":^\^"^\^"^},^\^"events^\^":^[^{^\^"shouldSendImediately^\^":true,^\^"id^\^":9,^\^"sid^\^":^\^"831842cc-2c72-48f3-a54e-8a49f8612313^\^",^\^"name^\^":^\^"AppOpenStatus^\^",^\^"type^\^":^\^"AppLifeCycle^\^",^\^"ts^\^":1696566433715,^\^"data^\^":^{^\^"Data^\^":^\^"Focus^\^"^}^}^],^\^"schemaVersion^\^":^\^"3.0^\^"^}" ^
  --compressed &
curl "https://api.asm.skype.com/v1/objects/0-sa-d6-d1754454c51db5164aa91d2078ae8983/views/original" ^
  -H "authority: api.asm.skype.com" ^
  -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "cookie: platformid_asm=1418; MSCC=NR; SC=CC=:CCY=INR:ENV=:LC=en-US:LIM=:RS=d:TM=1696566078:TS=1696566058257:TZ=:VAT=:VER=; x-csrf-token=543f758d-48e4-43a2-abca-baa766aafa07; skplet=1696652515; skypetoken_asm=eyJhbGciOiJSUzI1NiIsImtpZCI6IjVFODQ4MjE0Qzc3MDczQUU1QzJCREU1Q0NENTQ0ODlEREYyQzRDODQiLCJ4NXQiOiJYb1NDRk1kd2M2NWNLOTVjelZSSW5kOHNUSVEiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2OTY1NjYxMTUsImV4cCI6MTY5NjY1MjUxMywic2t5cGVpZCI6ImxpdmU6LmNpZC43ZWY2NDNlZjczNzNlOWUzIiwic2NwIjo5NTgsImNzaSI6IjE2OTY1NjYxMTMiLCJjaWQiOiI3ZWY2NDNlZjczNzNlOWUzIiwiYWF0IjoxNjk2MjM4NjcwfQ.cHYiY5m941BZAtkRviFbsbgGPKy5UVAWlpqgtk6g7tqLMHLz2VzkEZXVseIW-24czOTPNuJu9s-vXM1hHX9fxVQRSu-FQDN78GMjdj_tuht0gGL73OJrQWRDtwdfIVJUp5HksmqYyUTfpqUgpeRmYH-V7M1Aj1YgXzXhzGP41YIgKcmTcGMDq7RsJPICnVCgLxHnFGWCOp00GnoA_m22yXZjX2roesPpDm2UcqrwhGtjMndcp7kY5tUUywyqvIbtwU4cTsyHqmpROJw_Vnzcb2I6AwC3DQl3SgzXyQ9UhukmwUMuzKwF4sDpddXUulTh-F-ZN_JFHO_YdHSoN0ou_A" ^
  -H "referer: https://web.skype.com/" ^
  -H "sec-ch-ua: ^\^"Google Chrome^\^";v=^\^"117^\^", ^\^"Not;A=Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"117^\^"" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
  -H "sec-fetch-dest: document" ^
  -H "sec-fetch-mode: navigate" ^
  -H "sec-fetch-site: same-site" ^
  -H "sec-fetch-user: ?1" ^
  -H "upgrade-insecure-requests: 1" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" ^
  --compressed &
curl "https://azwcus1-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/^%^7B054b6547-1b60-4b9f-a21f-bdcd061aec24^%^7D/active" ^
  -H "Accept: application/json" ^
  -H "Accept-Language: en-US,en;q=0.9" ^
  -H "Authentication: skypetoken=eyJhbGciOiJSUzI1NiIsImtpZCI6IjVFODQ4MjE0Qzc3MDczQUU1QzJCREU1Q0NENTQ0ODlEREYyQzRDODQiLCJ4NXQiOiJYb1NDRk1kd2M2NWNLOTVjelZSSW5kOHNUSVEiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2OTY1NjYxMTUsImV4cCI6MTY5NjY1MjUxMywic2t5cGVpZCI6ImxpdmU6LmNpZC43ZWY2NDNlZjczNzNlOWUzIiwic2NwIjo5NTgsImNzaSI6IjE2OTY1NjYxMTMiLCJjaWQiOiI3ZWY2NDNlZjczNzNlOWUzIiwiYWF0IjoxNjk2MjM4NjcwfQ.cHYiY5m941BZAtkRviFbsbgGPKy5UVAWlpqgtk6g7tqLMHLz2VzkEZXVseIW-24czOTPNuJu9s-vXM1hHX9fxVQRSu-FQDN78GMjdj_tuht0gGL73OJrQWRDtwdfIVJUp5HksmqYyUTfpqUgpeRmYH-V7M1Aj1YgXzXhzGP41YIgKcmTcGMDq7RsJPICnVCgLxHnFGWCOp00GnoA_m22yXZjX2roesPpDm2UcqrwhGtjMndcp7kY5tUUywyqvIbtwU4cTsyHqmpROJw_Vnzcb2I6AwC3DQl3SgzXyQ9UhukmwUMuzKwF4sDpddXUulTh-F-ZN_JFHO_YdHSoN0ou_A" ^
  -H "BehaviorOverride: redirectAs404" ^
  -H "ClientInfo: os=Windows; osVer=10; proc=x86; lcid=en-US; deviceType=1; country=IN; clientName=skype4life; clientVer=1418/8.105.0.208//skype4life; timezone=Asia/Calcutta" ^
  -H "Connection: keep-alive" ^
  -H "Content-Type: application/json" ^
  -H "EndpointId: ^{054b6547-1b60-4b9f-a21f-bdcd061aec24^}" ^
  -H "Origin: https://web.skype.com" ^
  -H "Referer: https://web.skype.com/" ^
  -H "RegistrationToken: registrationToken=U2lnbmF0dXJlOjI6Mjg6QVFRQUFBRDRqbFo5c3ZWYTF3aXBCQ25HTi9rSztWZXJzaW9uOjY6MToxO0lzc3VlVGltZTo0OjE5OjUyNTAwMDc2NDc2MzA3NTIwNjk7RXAuSWRUeXBlOjc6MTo4O0VwLklkOjI6MjY6bGl2ZTouY2lkLjdlZjY0M2VmNzM3M2U5ZTM7RXAuRXBpZDo1OjM2OjA1NGI2NTQ3LTFiNjAtNGI5Zi1hMjFmLWJkY2QwNjFhZWMyNDtFcC5Mb2dpblRpbWU6NzoxOjA7RXAuQXV0aFRpbWU6NDoxOTo1MjUwMDA3NjQ3NjMwNzUyMDY5O0VwLkF1dGhUeXBlOjc6MjoxNTtFcC5FeHBUaW1lOjQ6MTk6NTI1MDAwODUxMTU1NzM4NzkwNDtFcC5Ta3lwZVRva2VuOjI6Njg4OmV5SmhiR2NpT2lKU1V6STFOaUlzSW10cFpDSTZJalZGT0RRNE1qRTBRemMzTURjelFVVTFRekpDUkVVMVEwTkVOVFEwT0RsRVJFWXlRelJET0RRaUxDSjROWFFpT2lKWWIxTkRSazFrZDJNMk5XTkxPVFZqZWxaU1NXNWtPSE5VU1ZFaUxDSjBlWEFpT2lKS1YxUWlmUS5leUpwWVhRaU9qRTJPVFkxTmpZeE1UVXNJbVY0Y0NJNk1UWTVOalkxTWpVeE15d2ljMnQ1Y0dWcFpDSTZJbXhwZG1VNkxtTnBaQzQzWldZMk5ETmxaamN6TnpObE9XVXpJaXdpYzJOd0lqbzVOVGdzSW1OemFTSTZJakUyT1RZMU5qWXhNVE1pTENKamFXUWlPaUkzWldZMk5ETmxaamN6TnpObE9XVXpJaXdpWVdGMElqb3hOamsyTWpNNE5qY3dmUS5jSFlpWTVtOTQxQlpBdGtSdmlGYnNiZ0dQS3k1VVZBV2xwcWd0azZnN3RxTE1ITHoyVnprRVpYVnNlSVctMjRjek9UUE51SnU5cy12WE0xaEhYOWZ4VlFSU3UtRlFETjc4R01qZGpfdHVodDBnR0w3M09KclFXUkR0d2RmSVZKVXA1SGtzbXFZeVVUZnBxVWdwZVJtWUgtVjdNMUFqMVlnWHpYaHpHUDQxWUlnS2NtVGNHTURxN1JzSlBJQ25WQ2dMeEhuRkdXQ09wMDBHbm9BX20yMnlYWmpYMnJvZXNQcERtMlVjcXJ3aEd0ak1uZGNwN2tZNXRVVXl3eXF2SWJ0d1U0Y1RzeUhxbXBST0p3X1ZuemNiMkk2QXdDM0RRbDNTZ3pYeVE5VWh1a213VU11ekt3RjRzRHBkZFhVdWxUaC1GLVpOX0pGSE9fWWRIU29OMG91X0E7VXNyLk5ldE1hc2s6MTE6MToyO1Vzci5YZnJDbnQ6NjoxOjA7VXNyLlJkcmN0RmxnOjI6MDo7VXNyLkV4cElkOjk6MTowO1Vzci5FeHBJZExhc3RMb2c6NDoxOjA7VXNlci5BdGhDdHh0OjI6NDQ4OkNsTnJlWEJsVkc5clpXNGFiR2wyWlRvdVkybGtMamRsWmpZME0yVm1Oek0zTTJVNVpUTUJBMVZwWXhReEx6RXZNREF3TVNBeE1qb3dNRG93TUNCQlRReE9iM1JUY0dWamFXWnBaV1RqNlhOejcwUDJmZ0FBQUFBQUFFQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQWFiR2wyWlRvdVkybGtMamRsWmpZME0yVm1Oek0zTTJVNVpUTUFBQUFBQUFBQUFBQUhUbTlUWTI5eVpRQUFBQUFFQUFBQUFBQUFBQUFBQUFEajZYTno3MFAyZmdBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQVJwc2FYWmxPaTVqYVdRdU4yVm1OalF6WldZM016Y3paVGxsTXdBQUFBQUFZWXNmWlFnQUFBQURWV2xqQ0Vsa1pXNTBhWFI1RGtsa1pXNTBhWFI1VlhCa1lYUmxDRU52Ym5SaFkzUnpEa052Ym5SaFkzUnpWWEJrWVhSbENFTnZiVzFsY21ObERVTnZiVzExYm1sallYUnBiMjRWUTI5dGJYVnVhV05oZEdsdmJsSmxZV1JQYm14NUFBQT07; expires=1696652513; endpointId=^{054b6547-1b60-4b9f-a21f-bdcd061aec24^}" ^
  -H "Sec-Fetch-Dest: empty" ^
  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Site: cross-site" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" ^
  -H "X-ECS-Etag: ^\^"ZJLCvwIoVVVrLRRR/TDjZd2NJChqUI1ksJdavyLuOyg=^\^"" ^
  -H "sec-ch-ua: ^\^"Google Chrome^\^";v=^\^"117^\^", ^\^"Not;A=Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"117^\^"" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
  --data-raw "^{^\^"timeout^\^":120^}" ^
  --compressed &
curl "https://gateway.bingviz.microsoftapp.net/receive?app=skype" ^
  -H "authority: gateway.bingviz.microsoftapp.net" ^
  -H "accept: */*" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "content-type: application/json" ^
  -H "origin: https://web.skype.com" ^
  -H "referer: https://web.skype.com/" ^
  -H "sec-ch-ua: ^\^"Google Chrome^\^";v=^\^"117^\^", ^\^"Not;A=Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"117^\^"" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: cross-site" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" ^
  --data-raw "^{^\^"dvid^\^":^\^"732b6fd7-ef81-49f0-9c10-b1e80a30033c^\^",^\^"meta^\^":^{^\^"advertisingId^\^":^\^"^\^",^\^"applicationId^\^":^\^"32EE78B3360B43588BFCD9818E60BBED^\^",^\^"build^\^":^\^"1418/8.105.0.208^\^",^\^"clientVersion^\^":^\^"8.105.0.208^\^",^\^"deviceModel^\^":^\^"Chrome^\^",^\^"deviceType^\^":^\^"117.0.0.0^\^",^\^"installId^\^":^\^"abc92135-33b0-4bfb-ad42-5a3a9f315381^\^",^\^"market^\^":^\^"en-US^\^",^\^"os^\^":^\^"Windows^\^",^\^"osVersion^\^":^\^"10^\^",^\^"timezone^\^":^\^"Asia/Calcutta^\^",^\^"extSchema^\^":^{^\^"user^\^":^{^\^"userSignedIn^\^":true,^\^"signinAccount^\^":^\^"S4LLive^\^",^\^"skypeId^\^":^\^"7EF643EF7373E9E3^\^"^}^},^\^"configuration^\^":^\^"1418^\^",^\^"flights^\^":^\^"^\^"^},^\^"events^\^":^[^{^\^"shouldSendImediately^\^":true,^\^"id^\^":10,^\^"sid^\^":^\^"831842cc-2c72-48f3-a54e-8a49f8612313^\^",^\^"name^\^":^\^"AppOpenStatus^\^",^\^"type^\^":^\^"AppLifeCycle^\^",^\^"ts^\^":1696566436356,^\^"data^\^":^{^\^"Data^\^":^\^"Blur^\^",^\^"dwellTime^\^":2640^}^}^],^\^"schemaVersion^\^":^\^"3.0^\^"^}" ^
  --compressed &
curl "https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application^%^2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.8.3&x-apikey=412067e7f99b4d5485bd95f98e2bdbfe-5b5e945b-a981-4c87-963f-cd6fe0410029-7280&client-time-epoch-millis=1696566437051&time-delta-to-apply-millis=1264" ^
  -H "authority: browser.pipe.aria.microsoft.com" ^
  -H "accept: */*" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "client-id: NO_AUTH" ^
  -H "content-type: application/bond-compact-binary" ^
  -H "origin: https://web.skype.com" ^
  -H "referer: https://web.skype.com/" ^
  -H "sdk-version: AWT-Web-JS" ^
  -H "sec-ch-ua: ^\^"Google Chrome^\^";v=^\^"117^\^", ^\^"Not;A=Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"117^\^"" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H "sec-ch-ua-platform: ^\^"Windows^\^"" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: cross-site" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" ^
  --data-raw ^"m	^J412067e7f99b4d5485bd95f98e2bdbfe-5b5e945b-a981-4c87-963f-cd6fe0410029-7280^

^I^act_default_source^©^$d35e1e15-6bb3-4844-bd26-a51c9324e451^Ñ^^ô^^ë^³^àb^Ë^^

^)^$b52c211b-b65a-4c5c-a412-37e6912f55e6q^^^ë^³^àb^©^custom^É^^app_open_status^Í
		^^Skype_InitiatingUser_IsGuest^N^Skype_InitiatingUser_Username^live:.cid.7ef643ef7373e9e3	ShellType^BrowserPlatformType^Windows^Version8.105.0.208^Platform_Uiversion^1418/8.105.0.208Platform_Id^1418^DeviceInfo.Make	117.0.0.0^DeviceInfo.Model^Chrome^ecs_etag.^\^"ZJLCvwIoVVVrLRRR/TDjZd2NJChqUI1ksJdavyLuOyg=^\^"NetworkType^Unknown^

session_id^$831842cc-2c72-48f3-a54e-8a49f8612313^AppInfo.ExperimentIds.P-R-1107341-2-5,P-R-1081482-2-3,P-R-22128-2-21^ChatEndpointId^$054b6547-1b60-4b9f-a21f-bdcd061aec24
DeviceInfo.Id^$abc92135-33b0-4bfb-ad42-5a3a9f315381^DeviceInfo.BrowserName^Chrome^DeviceInfo.BrowserVersion	117.0.0.0^MSACID^9148574388762962000	MSACIDHEX^7EF643EF7373E9E3^AppInfo.Language^en-US^UserInfo.Language^en-US^UserInfo.TimeZone^+05:30^DeviceInfo.OsName^Windows^DeviceInfo.OsVersion^10^AppInfo.Version8.105.0.208^EventInfo.InitId^$e22fcdf1-5d17-446d-b7f8-42c4bb3b7598^EventInfo.Sequence^51^EventInfo.SdkVersion^AWT-Web-JS-1.8.3^EventInfo.Name^app_open_status^EventInfo.Time^2023-10-06T04:27:16.357Z^Í^	^

^UserInfo.Id0^P^i^live:.cid.7ef643ef7373e9e3^

<img width="513" alt="skype_web" src="https://github.com/Terrance/SkPy/assets/143394015/1ab83a0c-7c5b-4b1b-adfa-dbd4038c9a4d">

**Comment by Terrance** [comment]
I've removed your paste as you leaked all of your tokens -- I'd suggest signing out of Skype for Web and resetting your password ASAP, and avoid pasting raw tokens in public places like GitHub in future.

The relevant request:

```
curl "https://api.asm.skype.com/v1/objects/0-sa-d6-.../views/original"
  ...
  -H "cookie: ..., skypetoken_asm=eyJhb..."
  ...
```

Looks like they may have switched to cookie authorisation instead of headers.  The existing header authorisation continues to work for me, but I've experimentally pushed branch `asm-cookie` which does the cookie authorisation instead (which also works for me so I'm hoping is valid for existing files).

Can you check if that branch works for you?

**Comment by goaucomp** [comment]
$ pip install git+https://github.com/Terrance/SkPy.git@asm-cookie
DEPRECATION: Loading egg at c:\users\91821\appdata\local\programs\python\python311\lib\site-packages\alright-2.5-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\91821\appdata\local\programs\python\python311\lib\site-packages\platformdirs-3.10.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Collecting git+https://github.com/Terrance/SkPy.git@asm-cookie
  Cloning https://github.com/Terrance/SkPy.git (to revision asm-cookie) to c:\cygwin64\tmp\pip-req-build-l2n06uo2
  Running command git clone --filter=blob:none --quiet https://github.com/Terrance/SkPy.git 'C:\cygwin64\tmp\pip-req-build-l2n06uo2'
  Running command git checkout -b asm-cookie --track origin/asm-cookie
  Branch 'asm-cookie' set up to track remote branch 'asm-cookie' from 'origin'.
  Switched to a new branch 'asm-cookie'
  Resolved https://github.com/Terrance/SkPy.git to commit 22443921bd1365d8032aba07c8a4c47a25b2708d
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4 in c:\users\91821\appdata\local\programs\python\python311\lib\site-packages (from SkPy==0.0.0) (4.12.2)
Requirement already satisfied: requests in c:\users\91821\appdata\local\programs\python\python311\lib\site-packages (from SkPy==0.0.0) (2.31.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\91821\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4->SkPy==0.0.0) (2.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\91821\appdata\local\programs\python\python311\lib\site-packages (from requests->SkPy==0.0.0) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\91821\appdata\local\programs\python\python311\lib\site-packages (from requests->SkPy==0.0.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\91821\appdata\local\programs\python\python311\lib\site-packages (from requests->SkPy==0.0.0) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\91821\appdata\local\programs\python\python311\lib\site-packages (from requests->SkPy==0.0.0) (2023.7.22)

I did run pip install command as above and re ran my listener, but no change in behavior. Am I missing anything here ?

**Comment by Terrance** [comment]
I can't tell from that output, as it doesn't shows SkPy itself actually being updated -- I'd expect after the various "Requirement already satisfied" messages something like...

```
Installing collected packages: SkPy
  Attempting uninstall: SkPy
    Found existing installation: SkPy 0.10.6
    Uninstalling SkPy-0.10.6:
      Successfully uninstalled SkPy-0.10.6
  Running setup.py develop for SkPy
Successfully installed SkPy-0.0.0
```

I also haven't seen the request made to download your file again this time -- as with the previous reports above, set `SKPY_DEBUG_HTTP=1` in your environment to actually log the request/response, and if you're running the updated branch then you should see the request as...

```
<= [11/10 23:52:52] GET https://xyz1-api.asm.skype.com/v1/objects/0-xyz-000-0000000000000000646c76a75b0e4cc1/views/original
{'cookies': {'skypetoken_asm': '***'}, 'headers': {}}
=> [11/10 23:52:52] 200
```
